"""Search metadata for PanWatch tools.

This metadata is intentionally separate from the model-facing JSON schemas.
The runtime can use it for discovery, while the host still owns executable
tool registration and permission decisions.
"""

from pan_agent import ToolRisk
from pan_agent_tool_research import ToolDataFreshness, ToolDescriptor


PANWATCH_TOOL_DESCRIPTORS: tuple[ToolDescriptor, ...] = (
    ToolDescriptor(
        tool_name="get_portfolio",
        title="查詢持倉",
        summary="查詢使用者實盤和模擬交易的持倉、倉位和組合摘要。",
        use_cases=["分析我的持倉", "檢視組合", "診斷持倉風險"],
        keywords=["持倉", "組合", "倉位", "帳戶", "投資組合"],
        aliases=["我的股票", "持有哪些股票", "看看持倉"],
        domain="portfolio",
        capabilities=["portfolio_read", "risk_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=500,
        output_summary="持倉摘要和風險相關資料。",
    ),
    ToolDescriptor(
        tool_name="get_stock_quote",
        title="查詢即時行情",
        summary="查詢一隻股票的最新價、漲跌幅和日內行情資料。",
        use_cases=["查詢股價", "檢視即時行情", "判斷當前價格"],
        keywords=["行情", "股價", "價格", "報價", "漲跌", "即時"],
        aliases=["查股價", "最新價", "股票現在多少錢"],
        entities=["股票程式碼", "市場"],
        domain="market_data",
        capabilities=["quote", "market_data"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=1_000,
        output_summary="最新價、漲跌幅和交易狀態。",
    ),
    ToolDescriptor(
        tool_name="find_research_candidates",
        title="發現研究候選",
        summary="從市場和持倉範圍中篩選值得進一步研究的股票候選及機會訊號。",
        use_cases=["發現投資機會", "篩選股票", "尋找研究候選"],
        keywords=["機會", "候選", "研究", "選股", "篩選", "訊號"],
        aliases=["發現機會", "找股票機會", "推薦研究標的"],
        domain="investment_research",
        capabilities=["candidate_discovery", "signal_screening", "research"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=3_000,
        output_summary="候選標的、評分、風險和入場計劃。",
    ),
    ToolDescriptor(
        tool_name="get_kline_summary",
        title="分析 K 線走勢",
        summary="獲取一隻股票的均線、動量和近期 K 線技術指標摘要。",
        use_cases=["分析技術面", "檢視趨勢", "判斷支撐壓力"],
        keywords=["K線", "技術分析", "均線", "趨勢", "動量", "支撐", "壓力"],
        aliases=["走勢", "技術面", "看圖"],
        domain="market_data",
        capabilities=["technical_analysis", "kline", "trend_analysis"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=1_500,
        output_summary="K 線指標、趨勢和支撐壓力摘要。",
    ),
    ToolDescriptor(
        tool_name="get_stock_news",
        title="檢索股票新聞",
        summary="檢索一隻股票最近七天的相關新聞、公告和訊息摘要。",
        use_cases=["查詢股票新聞", "檢視公司訊息", "瞭解最新公告"],
        keywords=["新聞", "資訊", "訊息", "公告", "輿情"],
        aliases=["最近有什麼新聞", "查公告", "看資訊"],
        domain="market_data",
        capabilities=["news", "event_research", "sentiment"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="近期新聞標題、來源和摘要。",
    ),
    ToolDescriptor(
        tool_name="search_stocks",
        title="搜尋股票標的",
        summary="按股票程式碼或名稱搜尋股票清單，確認標的程式碼和市場。",
        use_cases=["搜尋股票", "查股票程式碼", "確認股票名稱"],
        keywords=["搜尋股票", "股票程式碼", "股票名稱", "標的", "查程式碼"],
        aliases=["找股票", "搜一下股票", "這隻股票程式碼是多少"],
        entities=["股票程式碼", "股票名稱", "市場"],
        domain="market_data",
        capabilities=["symbol_search", "instrument_lookup"],
        data_freshness=ToolDataFreshness.STATIC,
        estimated_latency_ms=1_000,
        output_summary="匹配的股票程式碼、名稱和市場。",
    ),
    ToolDescriptor(
        tool_name="get_market_status",
        title="查詢市場狀態",
        summary="查詢 A 股、港股和美股當前交易狀態及交易時段。",
        use_cases=["檢視市場是否開盤", "查詢交易時間", "現在能交易嗎"],
        keywords=["開盤", "收盤", "交易時間", "交易狀態", "市場狀態"],
        aliases=["現在開市嗎", "今天開盤嗎", "市場開了嗎"],
        domain="market_data",
        capabilities=["market_status", "trading_calendar"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=100,
        output_summary="各市場交易狀態、時區和交易時段。",
    ),
    ToolDescriptor(
        tool_name="get_hot_stocks",
        title="查詢熱門股票",
        summary="按漲幅或成交額查詢指定市場的熱門股票榜單。",
        use_cases=["檢視熱門股票", "找漲幅靠前的股票", "看成交額排行"],
        keywords=["熱門股票", "漲幅榜", "成交額", "強勢股", "異動股"],
        aliases=["股票排行榜", "今天哪些股票熱門", "看看漲得好的股票"],
        entities=["市場", "排序方式", "數量"],
        domain="market_discovery",
        capabilities=["hot_stock_ranking", "market_screening"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="熱門股票、價格、漲跌幅、成交額和成交量。",
    ),
    ToolDescriptor(
        tool_name="get_hot_boards",
        title="查詢熱門板塊",
        summary="按漲幅、成交額或熱度查詢指定市場的熱門板塊和主題。",
        use_cases=["檢視熱門板塊", "尋找強勢行業", "瞭解市場主線"],
        keywords=["熱門板塊", "行業排行", "主題", "市場主線", "板塊漲幅"],
        aliases=["哪些板塊最強", "看行業熱點", "查板塊排行"],
        entities=["市場", "排序方式", "數量"],
        domain="market_discovery",
        capabilities=["hot_board_ranking", "theme_discovery"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="熱門板塊程式碼、名稱、漲跌幅和成交額。",
    ),
    ToolDescriptor(
        tool_name="get_board_stocks",
        title="查詢板塊成分股",
        summary="查詢指定板塊中按漲幅、成交額或熱度排序的成分股。",
        use_cases=["查看板塊成分股", "找板塊裡的強勢股", "分析行業個股"],
        keywords=["板塊成分股", "行業個股", "板塊股票", "板塊內排行"],
        aliases=["這個板塊有哪些股票", "看板塊裡的股票", "查板塊成分"],
        entities=["板塊程式碼", "排序方式", "數量"],
        domain="market_discovery",
        capabilities=["board_constituents", "board_screening"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_500,
        output_summary="板塊成分股、價格、漲跌幅、成交額和成交量。",
    ),
    ToolDescriptor(
        tool_name="get_stock_fundamentals",
        title="查詢股票基本面",
        summary="查詢一隻股票的估值、盈利、成長和財報期等基本面摘要。",
        use_cases=["分析基本面", "檢視估值", "查詢財務指標"],
        keywords=["基本面", "財務指標", "估值", "市盈率", "淨利潤", "ROE", "營收"],
        aliases=["看看公司基本面", "查財報指標", "估值怎麼樣"],
        entities=["股票程式碼", "市場"],
        domain="fundamentals",
        capabilities=["fundamentals", "valuation", "financials"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="估值、盈利、成長和最新財報期指標。",
    ),
    ToolDescriptor(
        tool_name="get_capital_flow",
        title="查詢資金流向",
        summary="查詢一隻股票的主力、超大單和大單等資金流向摘要。",
        use_cases=["檢視資金流向", "分析主力資金", "判斷資金進出"],
        keywords=["資金流", "主力資金", "淨流入", "大單", "超大單"],
        aliases=["主力在買入嗎", "資金進出怎麼樣", "看主力動向"],
        entities=["股票程式碼", "市場"],
        domain="market_data",
        capabilities=["capital_flow", "money_flow"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=2_000,
        output_summary="主力、超大單、大單和近 5 日資金流向。",
    ),
    ToolDescriptor(
        tool_name="get_dragon_tiger",
        title="查詢龍虎榜",
        summary="查詢指定交易日的龍虎榜上榜股票、上榜原因和買賣金額。",
        use_cases=["查詢龍虎榜", "檢視遊資動向", "分析上榜股票"],
        keywords=["龍虎榜", "上榜", "遊資", "機構席位", "淨買入"],
        aliases=["看龍虎榜", "今天龍虎榜", "查上榜股票"],
        entities=["交易日期", "市場"],
        domain="market_discovery",
        capabilities=["dragon_tiger", "institution_activity"],
        data_freshness=ToolDataFreshness.NEAR_REAL_TIME,
        estimated_latency_ms=2_500,
        output_summary="上榜股票、上榜原因、收盤表現和買賣金額。",
    ),
    ToolDescriptor(
        tool_name="get_price_alerts",
        title="查詢價格提醒",
        summary="查詢使用者已建立的價格提醒、觸發條件和啟用狀態。",
        use_cases=["檢視提醒", "查詢價格預警", "看看已有監控"],
        keywords=["提醒", "價格提醒", "預警", "監控", "觸發條件"],
        aliases=["我的提醒", "有哪些價格預警"],
        domain="price_alerts",
        capabilities=["alert_read", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        estimated_latency_ms=300,
        output_summary="提醒 ID、標的、條件和啟用狀態。",
    ),
    ToolDescriptor(
        tool_name="update_price_alert",
        title="修改價格提醒",
        summary="修改一條價格提醒的目標價、方向或啟用狀態。",
        use_cases=["修改提醒", "調整預警價格", "停用價格監控"],
        keywords=["修改提醒", "調整預警", "更新價格提醒"],
        aliases=["改提醒", "調整提醒條件"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["修改使用者價格提醒"],
    ),
    ToolDescriptor(
        tool_name="delete_price_alert",
        title="刪除價格提醒",
        summary="刪除一條價格提醒及其歷史命中記錄。",
        use_cases=["刪除提醒", "取消價格監控", "清理預警"],
        keywords=["刪除提醒", "取消提醒", "移除預警"],
        aliases=["刪掉提醒", "不要這個提醒了"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["刪除使用者價格提醒"],
    ),
    ToolDescriptor(
        tool_name="create_price_alert",
        title="建立價格提醒",
        summary="為已收錄的股票建立盤中價格提醒。",
        use_cases=["設定價格提醒", "建立價格預警", "監控突破或跌破"],
        keywords=["建立提醒", "設定提醒", "價格預警", "突破", "跌破"],
        aliases=["提醒我", "設定價格監控"],
        domain="price_alerts",
        capabilities=["alert_write", "user_settings"],
        data_freshness=ToolDataFreshness.REAL_TIME,
        risk=ToolRisk.WRITE,
        confirmation_required=True,
        side_effects=["建立使用者價格提醒"],
    ),
)
